### ISSUE TITLE
pls share how to run on Windows computer file  experiment.py

### ISSUE THREAD

**Issue by Sandy4321** [takuti/stream-recommender#1]
Please help to run some simple example 
different versions of  line to run file  experiment.py run gives error

details:
main path to project where file experiments located is 
d:\Recommender systems\code\stream-recommender-master\
pls see below errors    for 
1 
python experiment.py -f .\\config\\ML100k\\iMF.ini
2
python experiment.py -f  \\config\\ML100k\\iMF.ini
3
D:\Recommender systems\code\stream-recommender-master>python experiment.py -f D:\\Recommender systems\\code\\stream-recommender-master\\config\\ML100k\\iMF.ini
4
D:\Recommender systems\code\stream-recommender-master>python experiment.py -f "D:\Recommender systems\code\stream-recommender-master\config\ML100k\iMF.ini"
5
D:\Recommender systems\code\stream-recommender-master>python experiment.py -f config\ML100k\iMF.ini

6
may other variants can not run neither
python experiment.py -f .\\config\\example.ini
python experiment.py -f \\config\\example.ini 
python experiment.py -f .\config\example.ini
etc

D:\Recommender systems\code\stream-recommender-master>python experiment.py -f .\\config\\ML100k\\iMF.ini
Traceback (most recent call last):
  File "experiment.py", line 290, in <module>
    cli()
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "experiment.py", line 267, in cli
    exp = Runner(params=params, dataset=dataset, n_epoch=n_epoch)
  File "experiment.py", line 35, in __init__
    self.data = Converter().convert(dataset=dataset)
  File "D:\Recommender systems\code\stream-recommender-master\converter\converter.py", line 33, in convert
    c.convert()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 33, in convert
    self.__load_ratings()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 189, in __load_ratings
    with open(self.path['ratings'], encoding='ISO-8859-1') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Recommender systems\\code\\stream-recommender-master\\converter\\../data/ml-100k/u.data'

D:\Recommender systems\code\stream-recommender-master>python experiment.py -f config\\ML100k\\iMF.ini
Traceback (most recent call last):
  File "experiment.py", line 290, in <module>
    cli()
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "experiment.py", line 267, in cli
    exp = Runner(params=params, dataset=dataset, n_epoch=n_epoch)
  File "experiment.py", line 35, in __init__
    self.data = Converter().convert(dataset=dataset)
  File "D:\Recommender systems\code\stream-recommender-master\converter\converter.py", line 33, in convert
    c.convert()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 33, in convert
    self.__load_ratings()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 189, in __load_ratings
    with open(self.path['ratings'], encoding='ISO-8859-1') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Recommender systems\\code\\stream-recommender-master\\converter\\../data/ml-100k/u.data'

D:\Recommender systems\code\stream-recommender-master>

D:\Recommender systems\code\stream-recommender-master>python experiment.py -f D:\\Recommender systems\\code\\stream-recommender-master\\config\\ML100k\\iMF.ini
Usage: experiment.py [OPTIONS]

Error: Got unexpected extra argument (systems\\code\\stream-recommender-master\\config\\ML100k\\iMF.ini)

D:\Recommender systems\code\stream-recommender-master>

D:\Recommender systems\code\stream-recommender-master>python experiment.py -f "D:\Recommender systems\code\stream-recommender-master\config\ML100k\iMF.ini"
Traceback (most recent call last):
  File "experiment.py", line 290, in <module>
    cli()
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "experiment.py", line 267, in cli
    exp = Runner(params=params, dataset=dataset, n_epoch=n_epoch)
  File "experiment.py", line 35, in __init__
    self.data = Converter().convert(dataset=dataset)
  File "D:\Recommender systems\code\stream-recommender-master\converter\converter.py", line 33, in convert
    c.convert()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 33, in convert
    self.__load_ratings()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 189, in __load_ratings
    with open(self.path['ratings'], encoding='ISO-8859-1') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Recommender systems\\code\\stream-recommender-master\\converter\\../data/ml-100k/u.data'

D:\Recommender systems\code\stream-recommender-master>

D:\Recommender systems\code\stream-recommender-master>python experiment.py -f config\ML100k\iMF.ini
Traceback (most recent call last):
  File "experiment.py", line 290, in <module>
    cli()
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sander\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "experiment.py", line 267, in cli
    exp = Runner(params=params, dataset=dataset, n_epoch=n_epoch)
  File "experiment.py", line 35, in __init__
    self.data = Converter().convert(dataset=dataset)
  File "D:\Recommender systems\code\stream-recommender-master\converter\converter.py", line 33, in convert
    c.convert()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 33, in convert
    self.__load_ratings()
  File "D:\Recommender systems\code\stream-recommender-master\converter\MovieLens100k.py", line 189, in __load_ratings
    with open(self.path['ratings'], encoding='ISO-8859-1') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Recommender systems\\code\\stream-recommender-master\\converter\\../data/ml-100k/u.data'

D:\Recommender systems\code\stream-recommender-master>

**Comment by Sandy4321** [comment]
OK,
I run in IDE line by line 
and in file MovieLens100k
line 
  with open(self.path['ratings'], encoding='ISO-8859-1') as f:

from 
    def __load_ratings(self):
        """Load all samples in the dataset.

        """
        ratings = []
        with open(self.path['ratings'], encoding='ISO-8859-1') as f:
I see what is in variable
self.path['ratings']
'd:\\Recommender systems\\code\\stream-recommender-master\\converter\\../data/ml-100k/u.data'

So , you use Unix path style,
lets say I will override it 
but still please help to understand what file u.data is?
how to get it from ml-100k data?
Thanks a lot in advance

**Comment by takuti** [comment]
For Windows vs. UNIX path, yea, you need to overwrite the. Or, the FluRS package fixes the issue by [creating path with `os.path.join`](https://github.com/takuti/flurs/blob/33f08823b37e9ed4dfbfc3c72c817d021e813fbf/flurs/datasets/movielens.py#L40).

ML100k data is available at: https://grouplens.org/datasets/movielens/100k/ Once you download and decompress `ml-100k.zip`, the folder contains `u.data`.

**Comment by Sandy4321** [comment]
great thanks
